### ISSUE TITLE
Conflict with Uglify JS?

### ISSUE THREAD

**Issue by NiQ-B** [jkleinsc/broccoli-serviceworker#19]
Getting the following error with broccoli-serviceworker on 0.0.8 & 0.0.9. Fell back to version 0.0.7 and all builds fine. Minimum research stated that Unexpected token: punc() was related to uglify.js 

Fairly green to serviceworkers but got them working manually in ember but would really like to set it and for get it using a tool :-D. At least for the boilerplate.

I am using broccoli-static-compiler could be the conflict also.

Not sure where to start troubleshooting this error, here is the line in the service-worker.js
# BroccoliServiceWorker.prototype.write = function(readTree, destDir) {

ember s --proxy http://0.0.0.0:3000 --environment=production
version: 2.3.0
Proxying to http://0.0.0.0:3000
Livereload server on http://localhost:49154
Serving on http://localhost:4200/
File: service-worker.js (43:13)
Unexpected token: punc ())
Error
  at new JS_Parse_Error (<anonymous>:1508:18)
  at js_error (<anonymous>:1516:11)
  at croak (<anonymous>:2008:9)
  at token_error (<anonymous>:2016:9)
  at unexpected (<anonymous>:2022:9)
  at expr_atom (<anonymous>:2517:13)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at expr_atom (<anonymous>:2507:26)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at expr_list (<anonymous>:2540:24)
  at subscripts (<anonymous>:2674:30)
  at subscripts (<anonymous>:2651:20)
  at subscripts (<anonymous>:2671:20)
  at subscripts (<anonymous>:2651:20)
  at subscripts (<anonymous>:2671:20)
  at subscripts (<anonymous>:2651:20)
  at expr_atom (<anonymous>:2527:20)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at expr_list (<anonymous>:2540:24)
  at subscripts (<anonymous>:2674:30)
  at subscripts (<anonymous>:2651:20)
  at expr_atom (<anonymous>:2527:20)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at simple_statement (<anonymous>:2222:55)
  at eval (<anonymous>:2095:19)
  at eval (<anonymous>:2055:24)
  at block_ (<anonymous>:2335:20)
  at eval (<anonymous>:2308:25)
  at function_ (<anonymous>:2313:15)
  at expr_atom (<anonymous>:2521:24)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at expr_list (<anonymous>:2540:24)
  at subscripts (<anonymous>:2674:30)
  at subscripts (<anonymous>:2651:20)
  at expr_atom (<anonymous>:2527:20)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at simple_statement (<anonymous>:2222:55)
  at eval (<anonymous>:2095:19)
  at eval (<anonymous>:2055:24)
  at eval (<anonymous>:2802:23)
  at Object.parse (<anonymous>:2812:7)
  at /Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:62:33
  at Array.forEach (native)
  at Object.exports.minify (/Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:57:15)
  at UglifyWriter.processFile (/Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/broccoli-uglify-sourcemap/index.js:118:27)
  at /Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/broccoli-uglify-sourcemap/index.js:62:16
  at Array.forEach (native)
  at /Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/broccoli-uglify-sourcemap/index.js:52:21
  at lib$rsvp$$internal$$tryCatch (/Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/rsvp/dist/rsvp.js:1036:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/rsvp/dist/rsvp.js:1048:17)
  at lib$rsvp$$internal$$publish (/Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/rsvp/dist/rsvp.js:1019:11)
  at lib$rsvp$asap$$flush (/Users/<%home_directory%>/App/src/App-Platform/client/common/App-common/node_modules/rsvp/dist/rsvp.js:1198:9)
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickCallback (node.js:381:13)

**Comment by pete-the-pete** [comment]
I had the same issue, upgrading to ember-cli 2.40 solved it for me.
