### ISSUE TITLE
Service worker fail to build with --prod , when there is ES6 code

### ISSUE THREAD

**Issue by v3ss0n** [jkleinsc/broccoli-serviceworker#45]
If there is ES6 code , UglifyJS fails to build with `--prod`

**Comment by raucao** [comment]
Same for me with no custom worker code whatsoever:

```
Build failed.
The Broccoli Plugin: [UglifyWriter] failed with:
Error: ENOENT: no such file or directory, open '/home/basti/src/kosmos/hyperchannel/tmp/uglify_writer-input_base_path-Q3S0IHJE.tmp/sw-toolbox.js.map'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at UglifyWriter.processFile (/home/basti/src/kosmos/hyperchannel/node_modules/broccoli-uglify-sourcemap/index.js:119:40)
    at /home/basti/src/kosmos/hyperchannel/node_modules/broccoli-uglify-sourcemap/index.js:67:16
    at Array.forEach (native)
    at /home/basti/src/kosmos/hyperchannel/node_modules/broccoli-uglify-sourcemap/index.js:57:25
    at Array.forEach (native)
    at UglifyWriter.build (/home/basti/src/kosmos/hyperchannel/node_modules/broccoli-uglify-sourcemap/index.js:56:19)
    at /home/basti/src/kosmos/hyperchannel/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/home/basti/src/kosmos/hyperchannel/node_modules/rsvp/dist/rsvp.js:538:12)

The broccoli plugin was instantiated at:
    at UglifyWriter.Plugin (/home/basti/src/kosmos/hyperchannel/node_modules/broccoli-plugin/index.js:7:31)
    at new UglifyWriter (/home/basti/src/kosmos/hyperchannel/node_modules/broccoli-uglify-sourcemap/index.js:25:10)
    at UglifyWriter (/home/basti/src/kosmos/hyperchannel/node_modules/broccoli-uglify-sourcemap/index.js:20:12)
    at Class.postprocessTree (/home/basti/src/kosmos/hyperchannel/node_modules/ember-cli-uglify/index.js:15:50)
    at /home/basti/src/kosmos/hyperchannel/node_modules/ember-cli/lib/broccoli/ember-app.js:541:27
    at Array.forEach (native)
    at EmberApp.addonPostprocessTree (/home/basti/src/kosmos/hyperchannel/node_modules/ember-cli/lib/broccoli/ember-app.js:539:23)
    at EmberApp.toTree (/home/basti/src/kosmos/hyperchannel/node_modules/ember-cli/lib/broccoli/ember-app.js:1633:15)
    at module.exports (/home/basti/src/kosmos/hyperchannel/ember-cli-build.js:46:14)
    at Class.setupBroccoliBuilder (/home/basti/src/kosmos/hyperchannel/node_modules/ember-cli/lib/models/builder.js:74:19)
```

**Comment by raucao** [comment]
... actually, it turns out that when setting `debug` to `true`, it works. So it looks like a logical bug in the build code.

**Comment by urbany** [comment]
@skddc I added a PR to fix that: https://github.com/jkleinsc/broccoli-serviceworker/pull/48

**Comment by jkleinsc** [comment]
#48 resolved this issue if you specify sourcemaps: false in your ENV.serviceWorkersetting.

**Comment by urbany** [comment]
@jkleinsc actually I think the bug is the same I had, to solve it I actually need the sourcemaps, so it should be `sourcemaps: true` in the ENV.serviceWorkersetting.
